### ISSUE TITLE
MinimumConstraint only supports int

### ISSUE THREAD

**Issue by guilhermednt** [DoclerLabs/api-client-generator#39]
The following definition

```yaml
discount:
  type: number
  format: float
  minimum: 0.0
  maximum: 99.99
  example: 25.5
```

Causes the generation to fail because the constraint doesn't support `float`:

https://github.com/DoclerLabs/api-client-generator/blob/b8b0ed56a2e863716722a1d85dd7cf22f9495ab1/src/Entity/Constraint/MinimumConstraint.php#L16

However the spec supports it: https://swagger.io/docs/specification/data-models/data-types/#numbers

The same should happen with `maximum`:

https://github.com/DoclerLabs/api-client-generator/blob/b8b0ed56a2e863716722a1d85dd7cf22f9495ab1/src/Entity/Constraint/MaximumConstraint.php#L16
