### ISSUE TITLE
Using extensions to handle "soft enums"

### ISSUE THREAD

**Issue by JasonBenett** [DoclerLabs/api-client-generator#44]
Hello!

Currently, when the OpenApi spec defines an enum type, we are creating in the generated client a list of valid values. 

Imo, it would be interesting to be able to have an enum type in the spec (because this is the reality of the API) but, in the generated client, having a simple string instead. We could for example support openapi extensions like this:

```yaml
paths:
  '/v1/my/awesome/path':
    post:
      parameters:
        - schema:
             type: string
             enum: [value1, value2, value3]
             x-soft-enum: true
```

The main advantage is that when we add a new authorized value in the API, the client will not generate any error because it does not handles this value yet. If the value is not supported, the API is supposed to catch it. 

WDYT?
