### ISSUE TITLE
String Enum with integers fails abruptly

### ISSUE THREAD

**Issue by vsouz4** [DoclerLabs/api-client-generator#69]
wrong parameter (string enum with int values)
```
    EnabledFilter:
      in: query
      name: enabled
      schema:
        type: string
        enum:
          - 0
          - 1
```

Output from generator:
``` 
Backup original source.
 Restore original source from backup.
```

Expected: error message (e.g. "Error on mapping `enabled`: Only string enum fields are currently supported"). This message is already shown if you set type: integer instead.
